blank_issues_enabled: false
contact_links:
  - name: 📢 Discussions
    url: https://github.com/onihilist/NihilistShell/discussions
    about: Ask questions, share ideas, or discuss features here.
